import type { NextPage } from 'next'
import Head from 'next/head'
import { getAllDocs } from '../lib/helper'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <p className='font-serif'> Tailwind css + Next </p>
    </div>
  )
}

export default Home
